name: Build LaTex document
on: push

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Compile Latex document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          latexmk_use_xelatex: true
      - name: Check pdf files
        run: |
          file main.pdf | grep -q 'PDF'
          mv main.pdf Math-Note${{ steps.get_version.outputs.VERSION }}.pdf
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: PDF
          path: Math-Note${{ steps.get_version.outputs.VERSION }}.pdf
        if: always()
      - name: GH Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags')
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./Math-note${{ steps.get_version.outputs.VERSION }}.pdf